### ISSUE TITLE
Replace Buttons with mouse events

### ISSUE THREAD

**Issue by Kampii** [swagatblog/FabricJS_Drawing#1]
How tough would it be to implement that?

**Comment by swagatblog** [comment]
Could you please explain more on what do you want to achieve? An example would help

Cheers!!

**Comment by Kampii** [comment]
Hi,

So you have zoom in and zoom out buttons at the top. How can they be replaced so that a mouse scroll wheel could be used? Another thing.. For instance if a huge image is loaded, how to pan/ drag the view to see the different part of the image. Now when I zoom in and click the mouse to drag it actually moves the image. Does it makes sense?

**Comment by swagatblog** [comment]
Hey,

You can use mousewheel event to attach zoom listeners. There is an event property which would specify about its scroll up/down. based on which you can switch between zoomin and zoomout events.

Pan and drag approach is right. In case of bigger image, you can show image as is and can zoom/pan. 

Cheers!!
